#!/bin/bash

SCRIPT_DIR=$(dirname -- "$(readlink -- "$BASH_SOURCE")")
cd $SCRIPT_DIR;

MEDITATION_TIME=${1:-10}
BELL_TRACK=singing-bowl.mp3
TMPFILE=$(mktemp /tmp/meditation-journal.XXXXXX)
printf "Meditation Log\n\n\n" > ${TMPFILE}

echo Meditating for ${MEDITATION_TIME} minutes
afplay ${BELL_TRACK} && \
sleep $(( 60 * ${MEDITATION_TIME} )) &&
afplay ${BELL_TRACK} && \
vim ${TMPFILE} +3 && dayone new < ${TMPFILE}
rm -rf ${TMPFILE}
